-- 고양이와 개는 몇 마리 있을까
SELECT ANIMAL_TYPE, COUNT(*) AS count
FROM ANIMAL_INS
GROUP BY ANIMAL_TYPE
ORDER BY ANIMAL_TYPE;

-- 동명 동물 수 찾기
SELECT NAME, COUNT(*) AS COUNT
FROM ANIMAL_INS
WHERE NAME IS NOT NULL
GROUP BY NAME
HAVING COUNT(*) >= 2
ORDER BY NAME;

-- 입양 시각 구하기(1)
SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) BETWEEN 9 AND 20
GROUP BY HOUR(DATETIME)
ORDER BY HOUR(DATETIME)

-- 입양 시각 구하기(2)
WITH RECURSIVE T AS(
 SELECT 0 AS N
 UNION ALL
 SELECT N+1 FROM T
 WHERE N <23)
SELECT TA2.N AS HOUR, IFNULL(TA1.C,'0') AS COUNT
FROM T TA2 LEFT OUTER JOIN
			(SELECT HOUR(DATETIME) AS H, COUNT(*) AS C
			FROM ANIMAL_OUTS
			GROUP BY HOUR(DATETIME)) TA1
ON TA2.N = TA1.H;
